server:
  port: 8080

spring:
  application:
    name: GraphQL-Training-App
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:graphql-training
    username: sa
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 3000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
  exposed:
    generate-ddl: true

graphql:
  packages:
    - com.citicguoan.training.model
    - com.citicguoan.training.bll

logging:
  level:
    Exposed:
      DEBUG
